### ISSUE TITLE
Missing actual box art for Star Fox Command

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Nintendo_-_Nintendo_DS#193] opened 2022-05-20 18:57 UTC
New to this and am not sure how to be helpful vs annoying, but very interested in at least trying to help with this project however I can. There are snaps for this title, but the box art itself is missing. This one should work if there isn't another available.
![Star Fox Command (USA)](https://user-images.githubusercontent.com/105944840/169594226-ae681d18-2616-4b2c-b527-ea70e8f2637b.png)

**Comment by CrewMdk** [comment] 2022-05-22 06:18
Hello, I have already added the changes you mention in the following pull request: #197

You can close the issues.

**Comment by masanasake** [comment] 2022-05-22 11:53
Thank you for addressing these. I'm very new to this; Do you know how long it generally takes before these changes are reflected in the database? I'm not seeing them in the library on github, nor can they be accessed via retroarch as far as I can see. 
-------- Original message --------From: CrewMdk ***@***.***> Date: 5/22/22  1:18 AM  (GMT-06:00) To: libretro-thumbnails/Nintendo_-_Nintendo_DS ***@***.***> Cc: masanasake ***@***.***>, Author ***@***.***> Subject: Re: [libretro-thumbnails/Nintendo_-_Nintendo_DS] Missing actual box art for Star Fox Command (Issue #193) 
Hello, I have already added the changes you mention in the following pull request: #197
You can close the issues.

**Comment by masanasake** [comment] 2022-05-22 15:28
I figured out why I couldn't see them on here; branch defaulted to eef2262312 vs master. Still not sure why they don't appear via the "Download thumbnails" option in retroarch via steam. I know how the file associations work/how to manually add my own, but the goal was a permanent solution for the general populous. This is where retroarch is pulling the thumbnails from directly, right? Any ideas, or am I just in the wrong place?

**Comment by MarcoEstevez** [comment] 2022-05-23 06:01
I can't reproduce it:

rom name: Star Fox Command (USA, Australia)

I just added the rom and requested thumbnail for it

![image](https://user-images.githubusercontent.com/3447089/169752986-a7476b31-9a5e-42f7-97d9-74aae7eadadd.png)

[masanasake](https://github.com/masanasake) can you please test it again?

**Closed** 2022-05-24 21:34 UTC
